### ISSUE TITLE
Time to publish to crate.io

### ISSUE THREAD

**Issue by andelf** [GuillaumeGomez/c_vec-rs#12]
:) I need your new version!
current 1.1.0 on crate.io is broken under rust 1.0.0

**Comment by gkoz** [comment]
@andelf
You need the latest 1.0.x version, that branch maintains compatibility with Rust 1.0.

**Comment by GuillaumeGomez** [comment]
@gkoz was faster than me but it's just like he said.

**Comment by andelf** [comment]
thanks!
