### ISSUE TITLE
version 1.1.0?

### ISSUE THREAD

**Issue by durka** [GuillaumeGomez/c_vec-rs#13]
crates.io says the version is 1.1.0 but Cargo.toml here only goes up to 1.0.12. Did you publish to crates.io without pushing to Github?

**Comment by GuillaumeGomez** [comment]
Both versions are published. We had an issue about a type we used and wasn't available in rustc stable version.
@gkoz: Is this problem still occuring ?

**Comment by durka** [comment]
ptr::Unique is still unstable, yes.

**Comment by GuillaumeGomez** [comment]
Well, for now, please continue to use 1.0.12. We use this version in [rust-gnome/cairo](https://github.com/rust-gnome/cairo/blob/master/Cargo.toml#L32).

**Comment by GuillaumeGomez** [comment]
@durka: Can we close this issue ?

**Comment by durka** [comment]
Well, I put 1.0.12 in my Cargo.toml and beat cargo over the head with a tire iron until it used that version, and my crate compiles now. I haven't run it yet, though!

**Comment by GuillaumeGomez** [comment]
Ok! Then close it when you're sure everything's fine. ^^

**Comment by durka** [comment]
It works! As long you are careful to set a dependency on `c_vec = "= 1.0.12"`. Otherwise Cargo cannot restrain itself from downloading the "newer" 1.1.0.

**Comment by GuillaumeGomez** [comment]
Glad it worked ! :)
