### ISSUE TITLE
error: type `c_vec::CVec<u8>` does not implement any method in scope named `as_slice`

### ISSUE THREAD

**Issue by kornelski** [GuillaumeGomez/c_vec-rs#9]
Has `as_slice` been removed? I'm trying to upgrade form 1.0.4 to 1.0.11 and my code broke on this.

The example from the readme doesn't compile either.

**Comment by gkoz** [comment]
I believe `as_slice` everywhere was replaced with `as_ref`.

**Comment by GuillaumeGomez** [comment]
@pornel: Replace `as_slice` by `as_ref` and it should work just fine.

**Comment by GuillaumeGomez** [comment]
@pornel: And I updated the README file, thanks for that !

**Comment by kornelski** [comment]
Thank you.
